# Generated by Django 2.0.2 on 2018-02-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, max_length=200, verbose_name='videoID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('img_url', models.ImageField(blank=True, upload_to='artist', verbose_name='썸네일')),
            ],
        ),
    ]
