# Generated by Django 2.0.2 on 2018-02-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20180226_1307'),
        ('video', '0003_auto_20180227_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artist.Artist', verbose_name='아티스트 목록'),
        ),
    ]
