# Generated by Django 2.0.2 on 2018-02-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='앨범명')),
                ('img_cover', models.ImageField(blank=True, upload_to='album', verbose_name='커버 이미지')),
                ('release_date', models.DateField(verbose_name='발매일')),
                ('album_intro', models.TextField(blank=True, verbose_name='앨범소개')),
            ],
        ),
    ]
