# Generated by Django 2.0.2 on 2018-02-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
