# Generated by Django 2.0.2 on 2018-02-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_album_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='album', verbose_name='커버 이미지'),
        ),
    ]
