# Generated by Django 2.0.2 on 2018-02-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20180221_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='artist', verbose_name='프로필 이미지'),
        ),
    ]
